-- Neon Veins accounts (already applied to the D1 database; kept for reference / re-creation)
CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL UNIQUE COLLATE NOCASE, username TEXT NOT NULL UNIQUE COLLATE NOCASE, pass_hash TEXT NOT NULL, salt TEXT NOT NULL, iters INTEGER NOT NULL, color TEXT NOT NULL DEFAULT '#19f0ff', bio TEXT NOT NULL DEFAULT '', allow_requests INTEGER NOT NULL DEFAULT 1, show_online INTEGER NOT NULL DEFAULT 1, created INTEGER NOT NULL, last_seen INTEGER NOT NULL DEFAULT 0, activity TEXT NOT NULL DEFAULT '', join_code TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL, created INTEGER NOT NULL, expires INTEGER NOT NULL, device TEXT NOT NULL DEFAULT '');
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);
CREATE TABLE IF NOT EXISTS friends (a INTEGER NOT NULL, b INTEGER NOT NULL, state TEXT NOT NULL, requester INTEGER NOT NULL, created INTEGER NOT NULL, PRIMARY KEY (a, b));
CREATE INDEX IF NOT EXISTS friends_b ON friends(b);
CREATE TABLE IF NOT EXISTS saves (user_id INTEGER NOT NULL, slot TEXT NOT NULL, data TEXT NOT NULL, summary TEXT NOT NULL DEFAULT '', updated INTEGER NOT NULL, PRIMARY KEY (user_id, slot));
CREATE TABLE IF NOT EXISTS invites (id INTEGER PRIMARY KEY AUTOINCREMENT, from_id INTEGER NOT NULL, to_id INTEGER NOT NULL, code TEXT NOT NULL, created INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS invites_to ON invites(to_id);
CREATE TABLE IF NOT EXISTS attempts (k TEXT PRIMARY KEY, n INTEGER NOT NULL, since INTEGER NOT NULL);
